# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine
GAMEPROJECTFILE =/home/tonto/Repositories/UnrealEngine/ZombieApocalypse/ZombieApocalypse.uproject

TARGETS = \
	ZombieApocalypse-Linux-DebugGame  \
	ZombieApocalypse-Linux-Shipping  \
	ZombieApocalypse \
	ZombieApocalypseEditor-Linux-DebugGame  \
	ZombieApocalypseEditor-Linux-Shipping  \
	ZombieApocalypseEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/RunMono.sh" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool.exe"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend UnrealEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UnrealEditor-Linux-Debug


ZombieApocalypse-Linux-DebugGame:
	 $(PROJECTBUILD) ZombieApocalypse Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZombieApocalypse-Linux-Shipping:
	 $(PROJECTBUILD) ZombieApocalypse Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZombieApocalypse:
	 $(PROJECTBUILD) ZombieApocalypse Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZombieApocalypseEditor-Linux-DebugGame:
	 $(PROJECTBUILD) ZombieApocalypseEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZombieApocalypseEditor-Linux-Shipping:
	 $(PROJECTBUILD) ZombieApocalypseEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZombieApocalypseEditor:
	 $(PROJECTBUILD) ZombieApocalypseEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
